SELECT 
	bp.BO_POSTING_ID, 
	bp.POSTING_TYPE, 
	bp.BO_POSTING_TYPE,  
	bp.AMOUNT, 
	bp.TRANSFER_ID, 
	bp.LINKED_ID, 
	bp.EFFECTIVE_DATE, 
	bp.CURRENCY_CODE, 
	bp.DEBIT_ACC_ID AS "DEBIT_CLP_ACCOUNT", 
	aado.ACC_ACCOUNT_NAME AS "DEBIT_ACCOUNT_NAME", 
	aad.EXTERNAL_NAME AS "DEBIT_GL_ACCOUNT", 
	bp.CREDIT_ACC_ID AS "CREDIT_CLP_ACCOUNT", 
	aaco.ACC_ACCOUNT_NAME AS "CREDIT_ACCOUNT_NAME",
	aac.EXTERNAL_NAME AS "CREDIT_GL_ACCOUNT", 
	bp.SENT_DATE, 
	bp.SENT_STATUS
FROM 
	BO_POSTING bp
INNER JOIN 
	ACC_ACCOUNT aad 
	ON aad.ACC_ACCOUNT_ID = bp.DEBIT_ACC_ID  
INNER JOIN 
	ACC_ACCOUNT aado
	ON aado.ACC_ACCOUNT_ID = aad.ORIGINAL_ACCOUNT
INNER JOIN 
	ACC_ACCOUNT aac 
	ON aac.ACC_ACCOUNT_ID  = bp.CREDIT_ACC_ID 
INNER JOIN 
	ACC_ACCOUNT aaco
	ON aaco.ACC_ACCOUNT_ID = aac.ORIGINAL_ACCOUNT
WHERE bp.TRADE_ID = :trade_id
UNION ALL
SELECT 
	bp.BO_POSTING_ID, 
	bp.POSTING_TYPE, 
	bp.BO_POSTING_TYPE,  
	bp.AMOUNT, 
	bp.TRANSFER_ID, 
	bp.LINKED_ID, 
	bp.EFFECTIVE_DATE, 
	bp.CURRENCY_CODE, 
	bp.DEBIT_ACC_ID AS "DEBIT_CLP_ACCOUNT", 
	aad.ACC_ACCOUNT_NAME AS "DEBIT_ACCOUNT_NAME", 
	aad.EXTERNAL_NAME AS "DEBIT_GL_ACCOUNT", 
	bp.CREDIT_ACC_ID AS "CREDIT_CLP_ACCOUNT", 
	aac.ACC_ACCOUNT_NAME AS "CREDIT_ACCOUNT_NAME",
	aac.EXTERNAL_NAME AS "CREDIT_GL_ACCOUNT",
	bp.SENT_DATE, 
	bp.SENT_STATUS
FROM 
	BO_POSTING bp
INNER JOIN 
	ACC_ACCOUNT aad 
	ON aad.ACC_ACCOUNT_ID = bp.DEBIT_ACC_ID  
INNER JOIN 
	ACC_ACCOUNT aac 
	ON aac.ACC_ACCOUNT_ID  = bp.CREDIT_ACC_ID 
WHERE bp.TRADE_ID = :trade_id
AND bp.BO_POSTING_TYPE LIKE 'CST_%';